apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: javascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: javascriptdocker 
    spec:
      containers:
        - name: javascriptdocker 
          image: masterazurecontainerregistry.azurecr.io/javascriptdocker
          ports:
          - containerPort: 8080